apiVersion: apps/v1
kind: Deployment
metadata:
  name: funeral-agency-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: Funeral_Agency
  template:
    metadata:
      labels:
        app: Funeral_Agency
    spec:
      containers:
      - name: funeral-agency
        image: ahilottroya/funeral_agency:latest
        ports:
        - containerPort: 5000
        