name: Deploy to Minikube

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Start Minikube
        run: |
          minikube start --vm-driver=none
          kubectl config use-context minikube

      - name: Pull Docker Image from Docker Hub
        run: |
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/funeral_agency:latest
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Deploy to Minikube
        run: |
          kubectl apply -f k8s_manifests/

      - name: Wait for Deployment
        run: |
          kubectl rollout status deployment/Funeral_Agency_Deployment

      - name: Expose Service
        run: |
          minikube service Funeral_Agency_Node_Port

      - name: Stop Minikube
        run: minikube stop