name: Deploy to Minikube


on:
  workflow_run:
    workflows: ["Docker Image Build and Push"]
    types:
      - completed

jobs:
  setup-minikube:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install conntrack
        run: |
          sudo apt update
          sudo apt install -y conntrack


      - name: Install cri-tools
        run: |
          CRI_TOOLS_VERSION=$(curl -s https://api.github.com/repos/kubernetes-sigs/cri-tools/releases/latest | jq -r .tag_name)
          wget https://github.com/kubernetes-sigs/cri-tools/releases/download/${CRI_TOOLS_VERSION}/crictl-${CRI_TOOLS_VERSION}-linux-amd64.tar.gz
          tar zxvf crictl-${CRI_TOOLS_VERSION}-linux-amd64.tar.gz
          mv crictl /usr/local/bin/


      - name: Install cri-dockerd
        run: |
          CRI_DOCKERD_VERSION="0.3.8"
          curl -LO https://github.com/Mirantis/cri-dockerd/releases/tag/v${CRI_DOCKERD_VERSION}/cri-dockerd_${CRI_DOCKERD_VERSION}.amd64.tgz
          ls -lh cri-dockerd_${CRI_DOCKERD_VERSION}.amd64.tgz
          file cri-dockerd_${CRI_DOCKERD_VERSION}.amd64.tgz
          tar -tvf cri-dockerd_${CRI_DOCKERD_VERSION}.amd64.tgz
          tar -xf cri-dockerd_${CRI_DOCKERD_VERSION}.amd64.tgz
          sudo sh install_cri_dockerd.sh
          sudo systemctl start cri-dockerd
          sudo systemctl enable cri-dockerd
          

      - name: Start Minikube
        id: minikube
        run: |
          minikube start --vm-driver=none
          kubectl config use-context minikube

  deploy:
    runs-on: ubuntu-latest
    needs: setup-minikube

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Pull Docker Image from Docker Hub
        run: |
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/funeral_agency:latest
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Deploy to Minikube
        run: |
          kubectl apply -f k8s_manifests/

      - name: Wait for Deployment
        run: |
          kubectl rollout status deployment/Funeral_Agency_Deployment

      - name: Expose Service
        run: |
          minikube service Funeral_Agency_Node_Port

      - name: Stop Minikube
        run: minikube stop
