name: Deploy to Minikube


on:
  workflow_run:
    workflows: ["Docker Image Build and Push"]
    types:
      - completed

jobs:
  Deploy-To-Minikube:

    runs-on: ubuntu-latest
    name: Deploy Image to minikube

    steps:
    - uses: actions/checkout@v3

    - name: Start minikube
      uses: medyagh/setup-minikube@master

    - name: Try the cluster !
      run: kubectl get pods -A

    - name: Pull Docker Image from Docker Hub
      run: |
        docker pull ${{ secrets.DOCKERHUB_USERNAME }}/funeral_agency:latest
        docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Deploy to minikube
      run:
        kubectl apply -f k8s_manifests/

    - name: Wait for Deployment
      run: |
        kubectl rollout status deployment/Funeral_Agency_Deployment
    - name: Expose Service
      run: |
        minikube service Funeral_Agency_Node_Port
    - name: Stop Minikube
      run: | 
        minikube stop

