name: Docker Image Deployment

on:
  push:
    branches:
      - main

jobs:
  Build-Image:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/funeral_agency:latest .
        working-directory: .

  Scan-With-Trivy:
    runs-on: ubuntu-latest
    needs: [Build-Image]
    steps:
      - name: Install Trivy
        run: |
          wget https://github.com/aquasecurity/trivy/releases/download/v0.18.3/trivy_0.18.3_Linux-64bit.deb
          sudo dpkg -i trivy_0.18.3_Linux-64bit.deb
        working-directory: .

      - name: Trivy Scan
        run: trivy ${{ secrets.DOCKERHUB_USERNAME }}/funeral_agency:latest
        working-directory: .

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

  Use-Flake8:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12.0

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install flake8
        run: pip install flake8

      - name: Run flake8
        uses: py-actions/flake8@v2


  Use-MyPy:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12.0

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install MyPy
        run: pip install mypy

      - name: Run mypy
        uses: sasanquaneuf/mypy-github-action@releases/v1
        with:
          checkName: 'Use-MyPy'
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}

  Use-Ruff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Run Ruff
        uses: chartboost/ruff-action@v1

  Scan-With-SonarCloud:
    name: Scan with SonarCloud
    runs-on: ubuntu-latest

    needs: [Use-Flake8, Use-MyPy, Use-Ruff]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}


  Scan-With-Snyk:
    name: Scan with Snyk
    runs-on: ubuntu-latest
    needs: [Build-Image]
    steps:
      - name: Install Snyk
        run: npm install -g snyk

      - name: Snyk Scan
        run: snyk test --all-projects
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        working-directory: .


  Deploy-image:
    name: Deploy image to DockerHub
    
    runs-on: ubuntu-latest
    needs: [Build-Image, Scan-With-Trivy, Scan-With-SonarCloud, Scan-With-Snyk]
    
    steps:
      - name: Push Docker Image to Docker Hub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/funeral_agency:latest
